### ISSUE TITLE
Gray screen

### ISSUE THREAD

**Issue by karatemir** [and-viceversa/folium_offline#1]
Hi there,

I have tried using your script for rendering mbtiles downloaded from OpenMapTiles. I set up the http server and tried viewing the index.html file, however I am only getting a gray blank screen with the usual leaflet utilities. I've noticed that you mentioned this issue with mbtiles on [here](https://github.com/python-visualization/folium/issues/351#issuecomment-617261384). 

I've tried using firefox, chrome and edge on both windows10 and ubuntu but couldn't get the map to render, so I was wondering whether there is an easy fix here that I am overlooking.

Thanks a lot for your work.

**Comment by and-viceversa** [comment]
Hello @karatemir, please see my reply to the original thread  [here](https://github.com/python-visualization/folium/issues/351#issuecomment-774387495).

If you try to access your .mbtiles from a `file://` URL, the web browser will not honor the request due to security issues. When I originally tried this work around, some browsers had not patched the vulnerability yet.

Sorry for the late response - somehow I didn't get notification of the issue.
